# Generated by Django 4.0 on 2022-03-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserID', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Place_id', models.CharField(max_length=200)),
                ('Lat', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('Lng', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('UserID', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('Place_id', models.CharField(max_length=200)),
                ('Lat', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('Lng', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=2)),
                ('create_name', models.CharField(max_length=100)),
                ('create_uid', models.CharField(max_length=50)),
                ('accept_uid', models.CharField(max_length=50)),
                ('Lat', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('Lng', models.DecimalField(decimal_places=15, max_digits=18, null=True)),
            ],
        ),
    ]
